group:
  - files:
      - source: 觀察名單.csv
        dest:   觀察名單.csv
      - source: 觀察清單.csv
        dest:   觀察清單.csv
      - source: 未來競標名單.csv
        dest:   未來競標名單.csv
      - source: 已開標名單.csv
        dest:   已開標名單.csv
      - source: 未來競標清單.csv
        dest:   未來競標清單.csv
      - source: 已開標清單.csv
        dest:   已開標清單.csv
      - source: 專注名單.csv
        dest:   專注名單.csv
      - source: 觀察名單.csv
        dest:   觀察名單.csv
    repos: |
        wenchiehlee/GoPublic
        wenchiehlee/Selenium-Actions.Auction
