#.github/sync.yml
group:
  # 1st group
  - files:
      - source: .gitignore
        dest:   .gitignore
      - source: .github/workflows/sync-up.yml
        dest:   .github/workflows/sync-up.yml
      - source: .github/sync.yml
        dest:   .github/sync.yml
    repos: |
        wenchiehlee/mkdocs
        wenchiehlee/mkdocs-life
        wenchiehlee/mkdocs-investment
        wenchiehlee/GoogleSearch
        wenchiehlee/Python-Actions.PER
        wenchiehlee/Selenium-Actions.IPO
        wenchiehlee/Selenium-Actions.Auction
        wenchiehlee/twstock
        wenchiehlee/rss2md
        wenchiehlee/GoogleSearch
        wenchiehlee/FindMind
        wenchiehlee/Python-Actions.OpenAI
        ZhongZheng782/wenchiehlee.quickconnect.to
  # 2nd group
  - files:
      - source: CountCSVLine.py
        dest:   CountCSVLine.py
    repos: |
        wenchiehlee/Selenium-Actions.IPO
        wenchiehlee/Python-Actions.PER
        wenchiehlee/Selenium-Actions.Auction
