name: Sync-名單清單
on:
  workflow_dispatch:
  #schedule:
  #  - cron: "0 19 * * *"  # Runs every day at 7:00 PM UTC (3:00 AM Taipei time)
  push:
     branches:
       - main
     paths:
       - 觀察名單.csv                   # 僅在此檔案變更時觸發
       - 已開標名單.csv                 # 僅在此檔案變更時觸發
       - 未來競標名單.csv               # 僅在此檔案變更時觸發
       - 專注名單.csv                   # 僅在此檔案變更時觸發
       - 觀察名單.csv                   # 僅在此檔案變更時觸發
jobs:
  sync-backup-workflow:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4

      - name: Sync up
        uses: BetaHuhn/repo-file-sync-action@latest
        with:
          GH_PAT: ${{ secrets.REPO_FILE_SYNC_ACTION_DEPLOYMENTS }}
          CONFIG_PATH: .github/sync-名單清單.yml
          COMMIT_EACH_FILE: false
          PR_LABELS: "automated-sync"
          # Uncomment to skip Pull Request and push directly
          SKIP_PR: true
